---
title: "Housing Crisis"
output: html_notebook
---
```{r}
library(readr)
library(ggplot2)
library("tidyverse")
library("dplyr")
library("plotly")
```

1. Importing the Data
1.1. Housing Prices Database
```{r}
hpa <- read_csv("D:/DataScienceMBA/TCC/Database/HPA02.20220813T000818.csv", show_col_types = FALSE)
View(hpa)
names(hpa)

new_names <- c("Stat", "Year", "County","Dwelling", "Stamp", "Buyer", "Sale", "Unit", "Value")

names(hpa) <- new_names
head(hpa)

group_sale <- group_by(hpa, Sale, Year)
group_county <- group_by(hpa, County, Year)
group_stamp <- group_by(hpa, Stamp, Year)
group_dwelling <- group_by(hpa, Dwelling, Year)

by_sale <- group_sale  %>%summarise( ave = mean(Value,na.rm = TRUE) ,med = median(Value,na.rm = TRUE), max = max(Value,na.rm = TRUE), min = min(Value,na.rm = TRUE))


by_county <- group_county  %>% summarise( ave = mean(Value,na.rm = TRUE) ,med = median(Value,na.rm = TRUE), max = max(Value,na.rm = TRUE), min = min(Value,na.rm = TRUE))

group_stamp  %>% summarise( ave = mean(Value,na.rm = TRUE) ,med = median(Value,na.rm = TRUE), max = max(Value,na.rm = TRUE), min = min(Value,na.rm = TRUE))


group_dwelling  %>% summarise( ave = mean(Value,na.rm = TRUE) ,med = median(Value,na.rm = TRUE), max = max(Value,na.rm = TRUE), min = min(Value,na.rm = TRUE))

```

```{r}

interval <- 0:2022
hpa %>% filter (Year %in% interval) %>% 
ggplot(aes(x = factor(Year), y = Value, fill = factor(Sale))) + geom_boxplot(outlier.shape=NA) + facet_wrap(~Sale, nrow = 10) + xlab("Year")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +ylim(0, 500000)
```
```{r}

interval <- 2010:2022
hpa %>% filter (Year %in% interval) %>% 
ggplot(aes(x = factor(Year), y = Value, fill = factor(Dwelling))) + geom_boxplot(outlier.shape=NA) + facet_wrap(~Dwelling, nrow = 10) + theme(axis.text.x = element_text(angle = 45, hjust = 1)) +ylim(0, 500000)
```
```{r}

interval <- 2010:2022
hpa %>% filter (Year %in% interval) %>% 
ggplot(aes(x = factor(Year), y = Value, fill = factor(Stamp))) + geom_boxplot(outlier.shape=NA) + facet_wrap(~Stamp, nrow = 10) + theme(axis.text.x = element_text(angle = 45, hjust = 1)) +ylim(0, 500000)
```


```{r}

interval <- 2010:2022
hpa %>% filter (Year %in% interval) %>% 
ggplot(aes(x = factor(Year), y = Value, fill = factor(County))) + geom_boxplot(outlier.shape=NA) + facet_wrap(~County) +ylim(0, 500000)
```

```{r}

interval <- 2010:2022
p<-by_county %>% filter (Year %in% interval) %>% 
ggplot(aes(x =Year, y = med, group = County, color = factor(County))) + geom_line()  +ylim(0, 450000) + ylab("Median of House Values")
plotly::ggplotly(p)

```
